# Generated by Django 4.2.11 on 2024-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='letter',
            name='phonetic',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='letter',
            name='sound',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='letter',
            name='tamil',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='letter',
            name='type',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
